# Build stage (Java 21 để khớp Flink 2.2 + java21)
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests clean package

# Runtime stage (Flink base giống cluster)
FROM flink:2.2.0-scala_2.12-java21

RUN mkdir -p /opt/flink/usrlib

# Copy fat-jar vào usrlib
# Sửa đúng tên jar sau khi build (nên dùng shade plugin để ra 1 jar chạy được)
COPY --from=builder /build/target/*.jar /opt/flink/usrlib/credit-fraud-jobs.jar
