# Build stage
FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests clean package

# Runtime stage
FROM flink:1.20.1-scala_2.12-java11
WORKDIR /opt/flink
RUN mkdir -p /opt/flink/plugins/s3-fs-hadoop && cp /opt/flink/opt/flink-s3-fs-hadoop-*.jar /opt/flink/plugins/s3-fs-hadoop/
COPY --from=builder /build/target/credit-fraud-detection-1.0-SNAPSHOT.jar /opt/flink/app.jar

ENTRYPOINT ["flink", "run", "-c", "com.thesis.flinkapp.jobs.DataCleanerJob", "/opt/flink/app.jar"]
